//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BenhNhan : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.LuotKhams = new HashSet<LuotKham>();
            CMND = "";
            HoTen = "";
            GioiTinh = 1;
            SDT = "";
            DiaChi = "";
        }
    
        public string CMND { get; set; }
        public string HoTen { get; set; }
        public Nullable<byte> GioiTinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }

        public string cmnd1
        {
            get
            {
                return CMND;
            }
            set
            {
                CMND = value;
                Notify("cmnd1");
            }
        }

        public string hoten1
        {
            get
            {
                return HoTen;
            }
            set
            {
                HoTen = value;
                Notify("hoten1");
            }
        }
        public string sdt1
        {
            get
            {
                return SDT;
            }
            set
            {
                SDT = value;
                Notify("sdt1");
            }
        }
        public string diachi1
        {
            get
            {
                return DiaChi;
            }
            set
            {
                DiaChi = value;
                Notify("diachi1");
            }
        }
        public byte gioitinh1
        {
            get
            {
                return (byte)GioiTinh;
            }
            set
            {
                GioiTinh = value;
                Notify("diachi1");
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuotKham> LuotKhams { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        public void Notify(string v)
        {
            PropertyChanged?.Invoke(this,
                new PropertyChangedEventArgs(v));
        }
    }
}
