//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LuotThuoc : INotifyPropertyChanged
    {
        public LuotThuoc()
        {
            Thuoc = "";
            ID = -1;
            SoLuong = 0;
            LuotKham = -1;
        }
        public string thuoc2
        {
            get
            {
                return Thuoc;
            }
            set
            {
                Notify("thuoc2");
            }
        }
        public int soluong2
        {
            get
            {
                return (int)SoLuong;
            }
            set
            {
                SoLuong = value;
                Notify("soluong2");
            }
        }
        public int id2
        {
            get
            {
                return ID;
            }
            set
            {
                Notify("id2");
            }
        }

        public string Thuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> LuotKham { get; set; }
        public int ID { get; set; }

        public virtual LuotKham LuotKham1 { get; set; }
        public virtual Thuoc Thuoc1 { get; set; }


        public event PropertyChangedEventHandler PropertyChanged;
        public void Notify(string v)
        {
            PropertyChanged?.Invoke(this,
                new PropertyChangedEventArgs(v));
        }
    }
}
