//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LuotKham : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LuotKham()
        {
            this.LuotThuocs = new HashSet<LuotThuoc>();
            TienThuoc = 0;
            TienKham = 0;
            ID = -1;
            BenhNhan = "";
            NgayKham = "00/00/0000";
            Benh = "unidentified";
        }
    
        public int ID { get; set; }
        public string BenhNhan { get; set; }
        public string NgayKham { get; set; }
        public string Benh { get; set; }
        public Nullable<double> TienThuoc { get; set; }
        public Nullable<double> TienKham { get; set; }

        public double ChiPhi
        {
            get
            {
                return (double)TienThuoc + (double)TienKham;
            }
        }
        public virtual Benh Benh1 { get; set; }
        public virtual BenhNhan BenhNhan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuotThuoc> LuotThuocs { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        public void Notify(string v)
        {
            PropertyChanged?.Invoke(this,
                new PropertyChangedEventArgs(v));
        }
    }
}
